SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
VIRTSER_ENABLE = yes
# Not enough interupts, so something has to go
MOUSEKEY_ENABLE = no
# Don't use both shifts to enter command mode (see Space Cadet Shift in the qmk readme.md)
COMMAND_ENABLE = no
